#!/bin/bash
# 显示所有可用的训练脚本

echo "╔════════════════════════════════════════════════════════════╗"
echo "║          ShadowBox 训练脚本快速选择                        ║"
echo "║          Patrick's Parabox 风格 2D 渲染器                  ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "📋 可用脚本："
echo ""
echo "  0. ./test_new_renderer.sh - 测试新渲染器 (手动游玩)"
echo "     └─ 体验新的2D俯视图界面"
echo ""
echo "  1. ./test_curriculum.sh   - 测试课程学习 (500轮，快速升级)"
echo "     └─ 快速看到AI从Level 1升级到Level 5"
echo ""
echo "  2. ./test_viz.sh          - 测试可视化 (10轮训练)"
echo "     └─ 快速测试，确认环境正常"
echo ""
echo "  3. ./train_with_viz.sh    - 标准可视化训练 (60 FPS)"
echo "     └─ 推荐：平衡速度和观察效果"
echo ""
echo "  4. ./train_fast.sh        - 快速可视化训练 (120 FPS)"
echo "     └─ 快速观察AI学习过程"
echo ""
echo "  5. ./train_slow.sh        - 慢速可视化训练 (10 FPS)"
echo "     └─ 仔细观察每一步操作"
echo ""
echo "  6. ./train_no_viz.sh      - 无可视化训练"
echo "     └─ 最快速度，适合长时间训练"
echo ""
echo "════════════════════════════════════════════════════════════"
echo ""
echo "🎓 课程学习（Curriculum Learning）："
echo "  AI会从Level 1开始，逐步升级到Level 5"
echo "  升级条件："
echo "    - 最近10轮达到70%胜率，或"
echo "    - 达到该关卡的最大训练轮数"
echo "  详细说明: cat CURRICULUM_LEARNING_GUIDE.md"
echo ""
echo "🎨 新渲染器特点："
echo "  ✓ 清晰的2D俯视图（不再是伪3D）"
echo "  ✓ 颜色对应：红箱子→红目标点"
echo "  ✓ 目标点有脉冲动画，非常明显"
echo "  ✓ 箱子到位时显示✓标记"
echo "  ✓ 左侧UI面板显示所有信息"
echo "  ✓ 关卡进度条显示整体进度"
echo ""
echo "💡 提示："
echo "  - 首次使用请先运行: ./test_new_renderer.sh"
echo "  - 想快速看到多个关卡: ./test_curriculum.sh"
echo "  - 详细说明请查看: NEW_RENDERER_GUIDE.md"
echo "  - 关闭窗口可随时停止训练"
echo ""
echo "🚀 快速开始："
echo "  ./test_new_renderer.sh    # 先测试新界面"
echo "  ./test_curriculum.sh      # 测试课程学习"
echo "  ./train_with_viz.sh       # 然后开始正式训练"
echo ""
